
services:
  api:
    # Constrói a imagem a partir do Dockerfile no diretório atual ('.')
    build: .

    container_name: alura.yml
    # Mapeia a porta 8000 do seu computador para a porta 8000 do contêiner.
    ports:
      - "8000:8000"
    # Monta o diretório atual no diretório /app do contêiner para live-reloading.
    volumes:
      - .:/app
    # Comando para iniciar a aplicação com hot-reload, ideal para desenvolvimento.
    command: uvicorn app:app --host 0.0.0.0 --port 8000 --reload

